import { StyleSheet } from "react-native";

 const resStyles=StyleSheet.create({
    mainContainer:{
        flex:1,
        width:"100%",
        backgroundColor:"green",
        flexDirection:"column",
    },
    eachBox1:{
        flex:1,
        flexDirection:"row",
        flexWrap:"wrap",
        backgroundColor:"#F8A897"
    },
    commonText:{
        fontSize:20,
        color:"#fff",
        padding:5,
        fontWeight:"bold"
    },
    innerBox1:{
        flex:1,
        backgroundColor:"skyblue",
        margin:10,
    },
    innerBox2:{
        flex:1,
        backgroundColor:"blue",
        margin:10,
    },
    innerBox3:{
        flex:1,
        backgroundColor:"orange",
        margin:10,
    },
    eachBox2:{
        flex:1,
        backgroundColor:"#F07257",
    },
    button:{
        backgroundColor:"#bbb",
        color:"#fff",
        textAlign:"center",
        padding:10,
        margin:10,
        borderRadius:10,
        shadowColor:"red",
        elevation:10,
        shadowOpacity:1
    },
    success:{
      backgroundColor:"green",
    },
    primary:{
        backgroundColor:"blue",
      },
      warning:{
        backgroundColor:"gold",
      },
      error:{
        backgroundColor:"red",
      },
    eachBox3:{
        flex:1,
        backgroundColor:"#E05E42",
        padding:5,
    },
    eachBox4:{
        flex:1,
        backgroundColor:"#F85937",
        padding:5,
    },
    loaderMain:{
        flex:1,
    },
    eachBox5:{
        flex:1,
        backgroundColor:"#F04723",
        padding:5,
    },
    eachBox6:{
        flex:1,
        backgroundColor:"#F63207",
        padding:5,
    }
})

export default resStyles;